apiVersion: v1
kind: Pod
metadata:
  name: init-pod 
  labels:
    app: my-app
spec:
  initContainers:
  - name: init-container-1
    image: busybox
    command: ["sh", "-c", "echo Preparing environment; sleep 5"]
  - name: init-container-2
    image: busybox
    command: ["sh", "-c", "echo Downloading dependencies; sleep 5"]
  containers:
  - name: main-container
    image: nginx
    ports:
    - containerPort: 80

