apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  completions: 3
  parallelism: 1
  template:
    spec:
      containers:
        - name: my-task
          image: busybox
          command: ["echo", "Hello, Kubernetes!"]
      restartPolicy: Never

